### ISSUE TITLE
Problem 9 has some typos.

### ISSUE THREAD

**Issue by jaeyoo** [JackHidary/quantumcomputingbook#25]
1-(c). Projectors are $|0\rangle\langle0|$ and $|1\rangle\langle1|$. However, it says  $|0\rangle\langle0|$ and $`|0\rangle`\langle1|$. Also, it says the same thing twice. p(0) = \langle\psi|\Pi_0\psi\rangle and `p(0) = \langle\psi|\Pi_0\psi\rangle`. It should be `p(1) = \langle\psi|\Pi_1\psi\rangle`

3-(a) The problem seems to be about solving on <X*Y> but suddenly <X*Z> appears. Is it intended? where is 3-(b)?

**Comment by rmlarose** [comment]
Thanks @jaeyoo for pointing these out! Will fix now.
