### ISSUE TITLE
Typo in section 11.5

### ISSUE THREAD

**Issue by ara-medina** [JackHidary/quantumcomputingbook#27]
In the the first paragraph under equation 11.169 (on page 245), the text references "the first vector as a 1 x 2 matrix and the second vector as a 2 x 1 matrix" and later says "the product of a 1 x 2 matrix and a 2 x 1 matrix yields a 2 x 2 matrix". 

I believe the text needs to be changed to "the first vector as a 2 x 1 matrix and the second vector as a 1 x 2 matrix" and "the product of a 2 x 1 matrix and a 1 x 2 matrix yields a 2 x 2 matrix" ?

The matrices being referred to are shown in equation 11.167 (also on page 245), and the text right under 11.167 references the relevant matrices correctly I believe, calling them "a 2 x 1 matrix and a 1 x 2 matrix".

**Comment by rmlarose** [comment]
Thanks for the spotting this and the detailed note. 

> I believe the text needs to be changed to "the first vector as a 2 x 1 matrix and the second vector as a 1 x 2 matrix" and "the product of a 2 x 1 matrix and a 1 x 2 matrix yields a 2 x 2 matrix" ?

I agree this is correct. 

We will fix this and add an errata here.

**Comment by rmlarose** [comment]
Thank you again! This has been fixed and the correct text will appear in a new edition.
