### ISSUE TITLE
Numbering of chapters in repo differs from book

### ISSUE THREAD

**Issue by ekkards** [JackHidary/quantumcomputingbook#5]
Apparently the numbering of directories in the repo vs. chapters in the book does not match.

e.g. 
The book contains in chapter 9 "Quantum Computing Methods", with 9.1. VQE
whereas the repo has the Deutsch-Josza algorithm etc. 
https://github.com/JackHidary/quantumcomputingbook/blob/master/chapter09/cirq/deutsch-jozsa.py

This makes it tedious to find out whether code from the book is listed on the website or not, e.g. the VQE sample in pyQuil seems not to be here in the repo. Not in chapter 9, not in chapter 10, or should it be chapter 8?

**Comment by JackHidary** [comment]
thx - fixed

J
