### ISSUE TITLE
Missing code examples from the book

### ISSUE THREAD

**Issue by amirebrahimi** [JackHidary/quantumcomputingbook#6]
There are quite a few code examples, Ch.9 for instance, that are listed in the book in split up form, but aren't here on the site (e.g. Circ QAOA, quantum chemistry example). Will those be uploaded soon?

Also, some examples are mentioned where no code is given (e.g. Ch.8 Simon's Problem), but in the book mentions to check the website.

**Comment by rmlarose** [comment]
QAOA and quantum chemistry from Chp. 9 have been added. Simon's problem will be added soon.
